[package]
name    = "tun"
version = "0.4.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

description = "TUN device creation and handling."
repository  = "https://github.com/meh/rust-tun"
keywords    = ["tun", "network", "tunnel", "bindings"]

[dependencies]
libc        = "0.2"
error-chain = "0.11"

[target.'cfg(target_os = "linux")'.dependencies]
ioctl-sys = "0.5"
mio       = { version = "0.6", optional = true }
